# Digital Ocean App Platform Configuration
# This tells DO to use our unified container approach instead of auto-detecting services

name: rebelz-app
region: nyc

services:
  - name: app
    source_dir: /
    dockerfile_path: Dockerfile
    # github:
    #   repo: your-username/rebelzapp  # Replace with your actual repo
    #   branch: main
    http_port: 80
    instance_count: 1
    instance_size_slug: basic-xxs  # $5/month - can upgrade as needed
    
    envs:
      - key: ENV
        value: production
      - key: DEBUG
        value: "false"
      - key: ENABLE_DOCS
        value: "false"
      - key: MODEL_NAME
        value: gpt-4o-mini
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "60"
      - key: APP_NAME
        value: "Rebelz API"
      - key: MAX_FILE_SIZE
        value: "5242880"
      - key: RATE_LIMIT_CALLS
        value: "100"
      - key: RATE_LIMIT_PERIOD
        value: "60"
      # Add these in DigitalOcean App Platform UI:
      # - DATABASE_URL (your external PostgreSQL connection string)
      # - SECRET_KEY (generate with: python -c "import secrets; print(secrets.token_hex(32))")
      # - ALLOWED_ORIGINS (use ${_self.PUBLIC_URL} or your domain)
      # - OPENAI_API_KEY (already added)
      # - VITE_API_BASE_URL (use ${_self.PUBLIC_URL})

# Note: Using external DigitalOcean PostgreSQL database
# No managed databases needed in this configuration
