# Digital Ocean App Platform Configuration
# This tells DO to use our unified container approach instead of auto-detecting services

name: rebelz-app
region: nyc

services:
  - name: app
    source_dir: /
    dockerfile_path: Dockerfile
    # github:
    #   repo: your-username/rebelzapp  # Replace with your actual repo
    #   branch: main
    http_port: 80
    instance_count: 1
    instance_size_slug: basic-xxs  # $5/month - can upgrade as needed
    
    envs:
      - key: ENV
        value: production
      - key: DEBUG
        value: "false"
      - key: ENABLE_DOCS
        value: "false"
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}
      - key: SECRET_KEY
        value: ${SECRET_KEY}
      - key: ALLOWED_ORIGINS
        value: ${ALLOWED_ORIGINS}
      - key: POSTGRES_PASSWORD
        value: ${POSTGRES_PASSWORD}
      - key: REDIS_PASSWORD
        value: ${REDIS_PASSWORD}
      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}
      - key: MODEL_NAME
        value: gpt-4o-mini
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "60"
      - key: APP_NAME
        value: "Rebelz API"
      - key: MAX_FILE_SIZE
        value: "5242880"
      - key: RATE_LIMIT_CALLS
        value: "100"
      - key: RATE_LIMIT_PERIOD
        value: "60"
      - key: REDIS_URL
        value: ${redis.REDIS_URL}
      - key: VITE_API_BASE_URL
        value: ${_self.PUBLIC_URL}

databases:
  - name: db
    engine: PG
    version: "15"
    production: true
    size: basic

  - name: redis
    engine: REDIS
    version: "7"
    production: true
    size: basic
